apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel.fullname" . }}-env
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ .Values.app.key | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  MAIL_PASSWORD: {{ .Values.mail.password | quote }}
