{{- if .Values.queue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.fullname" . }}-worker
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.queue.replicaCount }}
  selector:
    matchLabels:
      {{- include "laravel.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "laravel.workerSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["php", "artisan", "queue:work", "--sleep=3", "--tries=3", "--max-time=3600"]
          envFrom:
            - configMapRef:
                name: {{ include "laravel.fullname" . }}-env
            - secretRef:
                name: {{ include "laravel.fullname" . }}-env
          {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
{{- end }}
